### ISSUE TITLE
Message body not showing at recipient 

### ISSUE THREAD

**Issue by cafeitduong** [securestate/king-phisher#282]
## Issue Description
HTML message body was showing properly in Preview mode, successfully delivered to recipient but just with 1 line "This message requires an HTML aware email agent to be properly viewed." if he/she opens it on a browser (Chrome).

## Reproduction Steps
1. Compose email body as below HTML in Error Detail section
2. Preview and send
3. On recipient side, open Gmail on browser, open the email.
4. See only "This message requires an HTML aware email agent to be properly viewed."

## Environment Details
Host OS: Ubuntu 14.04 LTS
King Phisher Version: 1.10.0 (rev: 63aaf4772ed9)

## Error Details / Stack Trace
 `Hello {{ client.first_name }},<br>`
`<br>`
`From the monitoring system, we found your account's password has been compromised.<br>`
`Please hurry to change your password by using <a href="{{url.webserver}}">this link.</a><br><br>
Please don't hesitate to contact IT Team if you have any question.<br><br>`
`Thanks,<br>`
`<br>
IT Team<br>`

**Comment by wolfthefallen** [comment]
Emails in HTML format require the email client to be able to render html. Not all email clients and/or emails services support rendering emails in HTML. Furthermore company can change settings in their email clients to prevent rendering of html formatted emails. 

Unfortunately there is no further support for an issue like this, as there is no control over what email client is being utilized or what that settings of the client are.

**Comment by zeroSteiner** [comment]
This does actually sound like an issue on our side @wolfthefallen. I'm thinking it's possibly related to this commit ef09d6da779915ce663b4a08005c289c60b68969. Can you see if you can reproduce it by sending an email to GMail?

**Comment by wolfthefallen** [comment]
Good catch, I'll give a try and see what happens.

**Comment by wolfthefallen** [comment]
@cafeitduong this issue has been resolved in commit 3b2540359b21bc4f1c214cf0631b1954f3cddb03. It is currently located in the dev branch if you would like to use it. Instruction for beta testing can be found at https://github.com/securestate/king-phisher/wiki/Updating-King-Phisher#beta-testing

**Comment by cafeitduong** [comment]
@wolfthefallen I followed below step to checkout the dev branch, install and restart the server, but message still not changed in Gmail on Chrome.

`[user@localhost king-phisher]$ git fetch origin
[user@localhost king-phisher]$ git checkout -b dev origin/dev
# if installing for the first time run the tools/install.sh script
[user@localhost king-phisher]$ sudo python3 -m pip install -r requirements.txt`

What should I do to pull more info for you to troubleshoot further, please let me know.

**Comment by wolfthefallen** [comment]
do a 'git log` to see what commit your branch is currently at.

If it is not on one of the following commits:
- Land #279, install script improvements
- Refactor install.sh echo messages
- Handle database authentication errors explicitely
- Fix to make HTML email priority

Run the following commands:
`git fetch origin`
`git pull origin dev`

**Comment by cafeitduong** [comment]
I'm currently on dev branch with those commits, however, running "./KingPhisher -L DEBUG" I have got below error.

`phisher@phishing:/opt/king-phisher$ ./KingPhisher -L DEBUG`
`Traceback (most recent call last):`
`File "./KingPhisher", line 49, in <module>`
`    from king_phisher.client import application`
`  File "/opt/king-phisher/king_phisher/client/__init__.py", line 76, in <module>`
`    raise RuntimeError("Missing required version for gi namespace '{0}'".format(namespace))`
`RuntimeError: Missing required version for gi namespace 'Vte'`

**Comment by wolfthefallen** [comment]
Changing to the dev branch should have not effected any of the gtk (gi) requirements. But it appears now that you are missing the Vte lib. This can be installed either by:
`sudo apt-get -y install gir1.2-vte-2.91`
or
`sudo apt-get -y install gir1.2-vte-2.90`

If you are using a new OS installation for the dev branch, you can run `sudo tools/install.sh`

**Comment by cafeitduong** [comment]
Ok let me try, but as the urgent of my project I have rolled back the client/server back to version 1.8.0 (working ok)
Please allow me couple days to try your suggests steps, while my campaign is done.

**Comment by cafeitduong** [comment]
I success installed "sudo apt-get -y install gir1.2-vte-2.90"
Running "./KingPhisher -L DEBUG" I found another error as below
```
phisher@phishing:/opt/king-phisher$ ./KingPhisher -L DEBUG
Traceback (most recent call last):
  File "./KingPhisher", line 49, in <module>
    from king_phisher.client import application
  File "/opt/king-phisher/king_phisher/client/application.py", line 55, in <module>
    from king_phisher.client import dialogs
  File "/opt/king-phisher/king_phisher/client/dialogs/__init__.py", line 35, in <module>
    from .clone_page import *
  File "/opt/king-phisher/king_phisher/client/dialogs/clone_page.py", line 37, in <module>
    from king_phisher.client.widget import extras
  File "/opt/king-phisher/king_phisher/client/widget/extras.py", line 172, in <module>
    class MultilineEntry(_Gtk_Frame):
  File "/opt/king-phisher/king_phisher/client/widget/extras.py", line 178, in MultilineEntry
    'text': (str, 'text', 'The contents of the entry.', '', GObject.ParamFlags.READWRITE),
AttributeError: type object 'PyGObjectParamFlags' has no attribute 'READWRITE'
```

**Comment by wolfthefallen** [comment]
@cafeitduong Thank you for following up. It keeps appearing that you are missing some requirements. While you are on the dev branch, make sure you do a `git fetch` and a `git pull` to make sure you are the lastest commit (he have made a couple more commits this week). The run `sudo tools/install.sh` from the King Phisher directory. Make sure you select Yes to keeping your database string.

**Comment by ndom91** [comment]
@cafeitduong I'm having the same issue with my client. I've pulled the dev branch and can confirm I got the commit s you referenced, in fact the newest one I got is:

<pre>
commit e08b930f5825eca2109793f62fb869bcae993098
Author: Spencer McIntyre <zeroSteiner@gmail.com>
Date:   Mon Apr 9 17:34:40 2018 -0400

    Tweak the output of tools/spf_check for alignment
</pre>

Any idea why I may still be seeing this? I know my client (evolution) can display html emails normally, and my smtp server supports it as well..

**Comment by ndom91** [comment]
I have the same result in evolution, the webmail client, and also in gmail web interface. It seems to be client independent.

**Comment by wolfthefallen** [comment]
I have tried to reproduce this issue on the latest commit from the dev branch, and have been unsuccessful. gmail, google inbox, outlook, evolution and a few other email services all are rendering the html message. 

Can you please start King Phisher Client in Debug mode `KingPhisher -L DEBUG`, and give me the first 20 our so lines of out put so I can see versions and plugins being loaded.

**Comment by ndom91** [comment]
KingPhisher client DEBUG output:

<pre>
DEBUG    king phisher version: 1.10.0 (rev: 63aaf4772ed9) python version: 3.6.3
DEBUG    client running in process: 3576 main tid: 0x7f9dac4d3740
DEBUG    using ui data from glade file: /opt/king-phisher/data/client/king_phisher/king-phisher-client.ui
DEBUG    gi.repository GLib version: 2.54.0
DEBUG    gi.repository GObject version: 3.24.1
DEBUG    gi.repository Gtk version: 3.22.25
DEBUG    gi.repository VTE version: 2.91
DEBUG    matplotlib version: 2.1.0
INFO     loading the config from: /home/ndo/.config/king-phisher/config.json
INFO     loading 1 plugins
DEBUG    plugin 'check_for_updates' has been loaded
DEBUG    client loaded in 0.00 seconds
DEBUG    resetting the gtk-theme-name property to it's default value
DEBUG    resetting the gtk-icon-theme-name property to it's default value
</pre>

Thanks!

**Comment by zeroSteiner** [comment]
Yeah that'd be the issue, you're not running the development version. You're on the mainline master branch where the fix hasn't been merged into yet.

**Comment by wolfthefallen** [comment]
From the debug out put it shows that you are running on the latest official release.
`DEBUG    king phisher version: 1.10.0 (rev: 63aaf4772ed9) python version: 3.6.3`

The current fix for this bug is in the `dev` branch. Please see [Beta Testing](https://github.com/securestate/king-phisher/wiki/Updating-King-Phisher#beta-testing) on instructions on how to switch to Dev branch. Once you have switch branches and pip installed the latest requirements, run King Phisher in DEBUG mode again and you should see `DEBUG    king phisher version: 1.11.0 (rev: e08b930f5825) python version: x.x.x.`

**Comment by ndom91** [comment]
Ohhh oyu know what, I moved my server to the dev version, but not the client (its running on a different machine) ;)

**Comment by zeroSteiner** [comment]
Yeah this fix was implemented client-side where is where the actual messages are sent.

**Comment by wolfthefallen** [comment]
As this fix is confirmed I am closing out this issue. @cafeitduong If you have issues changing to dev branch please open a new issue.
