### ISSUE TITLE
Error on Database Update

### ISSUE THREAD

**Issue by benichmt1** [securestate/king-phisher#346]
## Issue Description
When running a campaign using the latest dev version of the client and server, events that cause the database to update throw an error. For example, 1 error occurs for each message sent. This also occurs on visits and credential submission. 

Once the number of error messages grows over 400, the process crashes.

## Reproduction Steps
1. Start KP
2. Create a new campaign
3. Send email to list of targets in CSV format
4. Experience errors on cred submission, visit, and email row.

## Environment Details

Host OS: Fedora 28
King Phisher Version: Latest dev (1.13.0-beta3 (rev: c99a543a9df3))

## Error Details / Stack Trace
```
Error Type: builtins.AttributeError
Error Details: AttributeError("'tuple' object has no attribute 'insert'",)
Error UID: ab359007-3b51-40a4-bb6d-f0ab11ef3bc2
RPC Error: N/A (Not an RPC error)
King Phisher Version: 1.13.0-beta3 (rev: c99a543a9df3)
Platform Version: Linux: Fedora 28 Twenty Eight
Python Version: 3.6.8
Gtk Version: 3.22.30
Timezone: America/New_York

Thread Information:
===================
 => MainThread (alive=True daemon=False)
    Thread-7 (alive=True daemon=True)
    Thread-6 (alive=True daemon=False)
    Thread-11 (alive=True daemon=True)
    Thread-12 (alive=True daemon=True)

Stack Trace:
============
Traceback (most recent call last):
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/tabs/campaign.py", line 243, in signal_server_event_db
    row_data.insert(0, str(row.id))
AttributeError: 'tuple' object has no attribute 'insert'
```
```
WARNING  received server db event: updated for non-existent row messages:t2uuQBkxxCVyo8BN
ERROR    error uid: 74a1d077-a19c-4d51-8453-bcd94dd6748d an unhandled exception was thrown
Traceback (most recent call last):
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/tabs/campaign.py", line 243, in signal_server_event_db
    row_data.insert(0, str(row.id))
AttributeError: 'tuple' object has no attribute 'insert'
Fatal Python error: Cannot recover from stack overflow.

Thread 0x00007ff095fff700 (most recent call first):
  File "/usr/lib64/python3.6/ssl.py", line 587 in read
  File "/usr/lib64/python3.6/ssl.py", line 830 in read
  File "/usr/lib64/python3.6/ssl.py", line 968 in recv_into
  File "/usr/lib64/python3.6/socket.py", line 586 in readinto
  File "/usr/lib64/python3.6/smtplib.py", line 387 in getreply
  File "/usr/lib64/python3.6/smtplib.py", line 569 in data
  File "/usr/lib64/python3.6/smtplib.py", line 882 in sendmail
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/mailer.py", line 940 in send_message
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/mailer.py", line 909 in _try_send_message
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/mailer.py", line 882 in _send_messages
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/mailer.py", line 641 in run
  File "/usr/lib64/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/usr/lib64/python3.6/threading.py", line 884 in _bootstrap

Thread 0x00007ff092ff9700 (most recent call first):
  File "/home/anjuna/Tools/king-phisher/king_phisher/ssh_forward.py", line 95 in _handle
  File "/home/anjuna/Tools/king-phisher/king_phisher/ssh_forward.py", line 87 in handle
  File "/usr/lib64/python3.6/socketserver.py", line 724 in __init__
  File "/home/anjuna/Tools/king-phisher/king_phisher/ssh_forward.py", line 77 in __init__
  File "/usr/lib64/python3.6/socketserver.py", line 364 in finish_request
  File "/usr/lib64/python3.6/socketserver.py", line 654 in process_request_thread
  File "/usr/lib64/python3.6/threading.py", line 864 in run
  File "/usr/lib64/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/usr/lib64/python3.6/threading.py", line 884 in _bootstrap

Thread 0x00007ff0947fc700 (most recent call first):
  File "/usr/lib64/python3.6/selectors.py", line 376 in select
  File "/usr/lib64/python3.6/socketserver.py", line 236 in serve_forever
  File "/home/anjuna/Tools/king-phisher/king_phisher/ssh_forward.py", line 256 in run
  File "/usr/lib64/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/usr/lib64/python3.6/threading.py", line 884 in _bootstrap

Thread 0x00007ff09cffd700 (most recent call first):
  File "/home/anjuna/Tools/king-phisher/.venv/lib/python3.6/site-packages/paramiko/packet.py", line 288 in read_all
  File "/home/anjuna/Tools/king-phisher/.venv/lib/python3.6/site-packages/paramiko/packet.py", line 441 in read_message
  File "/home/anjuna/Tools/king-phisher/.venv/lib/python3.6/site-packages/paramiko/transport.py", line 1982 in run
  File "/usr/lib64/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/usr/lib64/python3.6/threading.py", line 884 in _bootstrap

Thread 0x00007ff0d7fff700 (most recent call first):
  File "/home/anjuna/Tools/king-phisher/king_phisher/ssh_forward.py", line 95 in _handle
  File "/home/anjuna/Tools/king-phisher/king_phisher/ssh_forward.py", line 87 in handle
  File "/usr/lib64/python3.6/socketserver.py", line 724 in __init__
  File "/home/anjuna/Tools/king-phisher/king_phisher/ssh_forward.py", line 77 in __init__
  File "/usr/lib64/python3.6/socketserver.py", line 364 in finish_request
  File "/usr/lib64/python3.6/socketserver.py", line 654 in process_request_thread
  File "/usr/lib64/python3.6/threading.py", line 864 in run
  File "/usr/lib64/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/usr/lib64/python3.6/threading.py", line 884 in _bootstrap

Thread 0x00007ff0fe004700 (most recent call first):
  File "/home/anjuna/Tools/king-phisher/.venv/lib/python3.6/site-packages/websocket/_app.py", line 51 in read
  File "/home/anjuna/Tools/king-phisher/.venv/lib/python3.6/site-packages/websocket/_app.py", line 291 in run_forever
  File "/usr/lib64/python3.6/threading.py", line 864 in run
  File "/home/anjuna/Tools/king-phisher/king_phisher/utilities.py", line 526 in run
  File "/usr/lib64/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/usr/lib64/python3.6/threading.py", line 884 in _bootstrap

Thread 0x00007ff100805700 (most recent call first):
  File "/usr/lib64/python3.6/selectors.py", line 376 in select
  File "/usr/lib64/python3.6/socketserver.py", line 236 in serve_forever
  File "/home/anjuna/Tools/king-phisher/king_phisher/ssh_forward.py", line 256 in run
  File "/usr/lib64/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/usr/lib64/python3.6/threading.py", line 884 in _bootstrap

Thread 0x00007ff0fb803700 (most recent call first):
  File "/home/anjuna/Tools/king-phisher/.venv/lib/python3.6/site-packages/paramiko/packet.py", line 288 in read_all
  File "/home/anjuna/Tools/king-phisher/.venv/lib/python3.6/site-packages/paramiko/packet.py", line 441 in read_message
  File "/home/anjuna/Tools/king-phisher/.venv/lib/python3.6/site-packages/paramiko/transport.py", line 1982 in run
  File "/usr/lib64/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/usr/lib64/python3.6/threading.py", line 884 in _bootstrap

Current thread 0x00007ff1778be540 (most recent call first):
  File "/usr/lib64/python3.6/logging/__init__.py", line 1413 in makeRecord
  File "/usr/lib64/python3.6/logging/__init__.py", line 1443 in _log
  File "/usr/lib64/python3.6/logging/__init__.py", line 1296 in debug
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/gui_utilities.py", line 804 in gtk_builder_get
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/gui_utilities.py", line 749 in _load_child_dependencies
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/gui_utilities.py", line 735 in __init__
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 169 in __init__
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 193 in _interact_on_idle
  File "/home/anjuna/Tools/king-phisher/.venv/lib/python3.6/site-packages/gi/overrides/Gtk.py", line 550 in run
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 187 in interact
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 194 in _interact_on_idle
  File "/home/anjuna/Tools/king-phisher/.venv/lib/python3.6/site-packages/gi/overrides/Gtk.py", line 550 in run
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 187 in interact
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 194 in _interact_on_idle
  File "/home/anjuna/Tools/king-phisher/.venv/lib/python3.6/site-packages/gi/overrides/Gtk.py", line 550 in run
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 187 in interact
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 194 in _interact_on_idle
  File "/home/anjuna/Tools/king-phisher/.venv/lib/python3.6/site-packages/gi/overrides/Gtk.py", line 550 in run
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 187 in interact
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 194 in _interact_on_idle
  File "/home/anjuna/Tools/king-phisher/.venv/lib/python3.6/site-packages/gi/overrides/Gtk.py", line 550 in run
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 187 in interact
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 194 in _interact_on_idle
  File "/home/anjuna/Tools/king-phisher/.venv/lib/python3.6/site-packages/gi/overrides/Gtk.py", line 550 in run
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 187 in interact
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 194 in _interact_on_idle
  File "/home/anjuna/Tools/king-phisher/.venv/lib/python3.6/site-packages/gi/overrides/Gtk.py", line 550 in run
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 187 in interact
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 194 in _interact_on_idle
  File "/home/anjuna/Tools/king-phisher/.venv/lib/python3.6/site-packages/gi/overrides/Gtk.py", line 550 in run
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 187 in interact
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 194 in _interact_on_idle
  File "/home/anjuna/Tools/king-phisher/.venv/lib/python3.6/site-packages/gi/overrides/Gtk.py", line 550 in run
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 187 in interact
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 194 in _interact_on_idle
  File "/home/anjuna/Tools/king-phisher/.venv/lib/python3.6/site-packages/gi/overrides/Gtk.py", line 550 in run
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 187 in interact
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 194 in _interact_on_idle
  File "/home/anjuna/Tools/king-phisher/.venv/lib/python3.6/site-packages/gi/overrides/Gtk.py", line 550 in run
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 187 in interact
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 194 in _interact_on_idle
  File "/home/anjuna/Tools/king-phisher/.venv/lib/python3.6/site-packages/gi/overrides/Gtk.py", line 550 in run
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 187 in interact
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 194 in _interact_on_idle
  File "/home/anjuna/Tools/king-phisher/.venv/lib/python3.6/site-packages/gi/overrides/Gtk.py", line 550 in run
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 187 in interact
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 194 in _interact_on_idle
  File "/home/anjuna/Tools/king-phisher/.venv/lib/python3.6/site-packages/gi/overrides/Gtk.py", line 550 in run
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 187 in interact
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 194 in _interact_on_idle
  File "/home/anjuna/Tools/king-phisher/.venv/lib/python3.6/site-packages/gi/overrides/Gtk.py", line 550 in run
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 187 in interact
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 194 in _interact_on_idle
  File "/home/anjuna/Tools/king-phisher/.venv/lib/python3.6/site-packages/gi/overrides/Gtk.py", line 550 in run
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 187 in interact
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 194 in _interact_on_idle
  File "/home/anjuna/Tools/king-phisher/.venv/lib/python3.6/site-packages/gi/overrides/Gtk.py", line 550 in run
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 187 in interact
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 194 in _interact_on_idle
  File "/home/anjuna/Tools/king-phisher/.venv/lib/python3.6/site-packages/gi/overrides/Gtk.py", line 550 in run
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 187 in interact
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 194 in _interact_on_idle
  File "/home/anjuna/Tools/king-phisher/.venv/lib/python3.6/site-packages/gi/overrides/Gtk.py", line 550 in run
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 187 in interact
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 194 in _interact_on_idle
  File "/home/anjuna/Tools/king-phisher/.venv/lib/python3.6/site-packages/gi/overrides/Gtk.py", line 550 in run
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 187 in interact
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 194 in _interact_on_idle
  File "/home/anjuna/Tools/king-phisher/.venv/lib/python3.6/site-packages/gi/overrides/Gtk.py", line 550 in run
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 187 in interact
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 194 in _interact_on_idle
  File "/home/anjuna/Tools/king-phisher/.venv/lib/python3.6/site-packages/gi/overrides/Gtk.py", line 550 in run
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 187 in interact
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 194 in _interact_on_idle
  File "/home/anjuna/Tools/king-phisher/.venv/lib/python3.6/site-packages/gi/overrides/Gtk.py", line 550 in run
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 187 in interact
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 194 in _interact_on_idle
  File "/home/anjuna/Tools/king-phisher/.venv/lib/python3.6/site-packages/gi/overrides/Gtk.py", line 550 in run
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 187 in interact
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 194 in _interact_on_idle
  File "/home/anjuna/Tools/king-phisher/.venv/lib/python3.6/site-packages/gi/overrides/Gtk.py", line 550 in run
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 187 in interact
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 194 in _interact_on_idle
  File "/home/anjuna/Tools/king-phisher/.venv/lib/python3.6/site-packages/gi/overrides/Gtk.py", line 550 in run
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 187 in interact
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 194 in _interact_on_idle
  File "/home/anjuna/Tools/king-phisher/.venv/lib/python3.6/site-packages/gi/overrides/Gtk.py", line 550 in run
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 187 in interact
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 194 in _interact_on_idle
  File "/home/anjuna/Tools/king-phisher/.venv/lib/python3.6/site-packages/gi/overrides/Gtk.py", line 550 in run
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 187 in interact
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 194 in _interact_on_idle
  File "/home/anjuna/Tools/king-phisher/.venv/lib/python3.6/site-packages/gi/overrides/Gtk.py", line 550 in run
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 187 in interact
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 194 in _interact_on_idle
  File "/home/anjuna/Tools/king-phisher/.venv/lib/python3.6/site-packages/gi/overrides/Gtk.py", line 550 in run
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 187 in interact
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 194 in _interact_on_idle
  File "/home/anjuna/Tools/king-phisher/.venv/lib/python3.6/site-packages/gi/overrides/Gtk.py", line 550 in run
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/dialogs/exception.py", line 187 in interact
  ...
[1]    12721 abort (core dumped)  ./KingPhisher
```

**Comment by zeroSteiner** [comment]
Well the stack-overflow is concerning but I'm highly confident that the underlying issue is the fact that various classes that inherit from `CampaignViewGenericTableTab` are returning tuples from their `format_node_data` methods. This is then causing an issue in `signal_server_event_db` when the result is being treated as a list.

I'll have a fix pushed up shortly.

**Comment by zeroSteiner** [comment]
Fixed in commit ce11258b23d8ccc25ca87e8e1c284f851119ac32.

This issue has now been fixed in the dev branch. To obtain the changes, you can either wait for them to be merged into the master branch (which will likely take a few weeks) or you can obtain them immediately by opting into [beta testing](https://github.com/securestate/king-phisher/wiki/Updating-King-Phisher#beta-testing).

**Comment by benichmt1** [comment]
Thanks! 

I was able to successfully launch a campaign without errors. When removing rows I still get the following trace:

```Error Type: builtins.TypeError
Error Details: TypeError('unknown type (null)',)
Error UID: a7dbbf92-a01e-4f8a-bf54-d3ee2efe92d4
RPC Error: N/A (Not an RPC error)
King Phisher Version: 1.13.0-beta3 (rev: ce11258b23d8)
Platform Version: Linux: Fedora 28 Twenty Eight
Python Version: 3.6.8
Gtk Version: 3.22.30
Timezone: America/New_York

Thread Information:
===================
 => MainThread (alive=True daemon=False)
    Thread-7 (alive=True daemon=True)
    Thread-6 (alive=True daemon=False)
    Thread-11 (alive=True daemon=True)
    Thread-12 (alive=True daemon=True)

Stack Trace:
============
Traceback (most recent call last):
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/widget/managers.py", line 378, in signal_activate_popup_menu_delete
    self._call_cb_delete()
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/widget/managers.py", line 258, in _call_cb_delete
    self.cb_delete(self.treeview, selection)
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/tabs/campaign.py", line 272, in _prompt_to_delete_row
    row_ids = [self._tv_model.get_value(ti, 0) for ti in gui_utilities.gtk_treeview_selection_iterate(treeview)]
  File "/home/anjuna/Tools/king-phisher/king_phisher/client/tabs/campaign.py", line 272, in <listcomp>
    row_ids = [self._tv_model.get_value(ti, 0) for ti in gui_utilities.gtk_treeview_selection_iterate(treeview)]
TypeError: unknown type (null)```

Is that related to a mismatch in an already existing campaign?

**Comment by zeroSteiner** [comment]
I'm pretty sure that's a different issue. I'll take a look now and see what I can find.

**Comment by zeroSteiner** [comment]
Fixed in commit faac7130904264c096e0cbf203f2d41e27ea29bf.

This bug is due to the treeiter being associated with treeview model which is filtered and no longer the exact same as the one referenced in `self._tv_model`.
