### ISSUE TITLE
SSH authentication error 

### ISSUE THREAD

**Issue by thesle3p** [securestate/king-phisher#81]
Hi, so this is new, when ever I try and connect to king Phisher server via the client (using a passworded account over ssh)  it hangs for a minute and then brings me back to the ssh connection window and when I look at the console output from the server I get the following warning

```
WARNING  <connecting IP> code 400, message Bad request syntax ('SSH-2.0-paramiko_1.16.0')
INFO     <connecting IP> "SSH-2.0-paramiko_1.16.0" 400 -
```

Any idea what is going on there?

**Comment by zeroSteiner** [comment]
It looks like you're trying to SSH into the HTTP port. Ensure that in the client connection dialog, Server is set to "12.34.56.78:22" (notice the 22 specifies the SSH port for the King Phisher server). Then ensure that the HTTP port is left at 80 or whatever port you set the server to listen on.

**Comment by thesle3p** [comment]
Now I feel silly, thought I put 22 there..... :-[

**Comment by zeroSteiner** [comment]
@thesle3p does that mean this issue has been resolved?

**Comment by thesle3p** [comment]
Nope, issue still persists: I get the following error from the gui:
```
Failed To Connect To The King Phisher RPC Service
Ensure that the King Phisher Server is currently running.

WARNING  failed to connect to the remote rpc service
```

and this stack trace from the client's command line:
```
Traceback (most recent call last):
  File "/path/to/king-phisher/king_phisher/client/application.py", line
471, in server_connect
    server_version_info = rpc('version')
  File "/usr/local/lib/python2.7/dist-packages/AdvancedHTTPServer.py",
line 495, in __call__
    return self.call(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/AdvancedHTTPServer.py",
line 546, in call
    resp = self.client.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1073, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 379, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''
```

There is no entry in King-Phishers log file.

**Comment by zeroSteiner** [comment]
The client can't connect to the RPC / HTTP interface. Is the server listening on the configured port and are you trying to use SSL? Also is the server local or remote?

**Comment by itmaniac** [comment]
Hi Zero Steiner, 
I have installed the King Phisher tool but whenever i tried to run the kingphisherserver file with config_file.csv ,it through me error that there is some issue with the config_file.csv. i created this config_file under gedit application and saved it as UTF8 format and CSV extension but still having problem. kindly help me in this regards.

**Comment by itmaniac** [comment]
![Uploading config_file error.png…]()
![Uploading config_file error.jpg…]()

**Comment by zeroSteiner** [comment]
itmaniac the issue that you are describing us unrelated to this thread. Please open a new issue to discuss it. Additionally the server's configuration file is a YAML file not CSV. Please refer to the documentation provided in the project wiki.

**Comment by zeroSteiner** [comment]
Have you had a chance to look at this any more @thesle3p and are you still experiencing issues?

**Comment by thesle3p** [comment]
Will look at it some more when I can.

-----Original Message-----

**Comment by zeroSteiner** [comment]
When you're ready to look at it again just reply on this thread and I'll reopen the issue.

**Comment by seanjackson** [comment]
Zero steiner  am having same issue when using Kingphisher.Seems like i have done everything but iy not connecting
Nope, issue still persists: I get the following error from the gui:

Failed To Connect To The King Phisher RPC Service
Ensure that the King Phisher Server is currently running.

WARNING  failed to connect to the remote rpc service
and this stack trace from the client's command line:

Traceback (most recent call last):
  File "/path/to/king-phisher/king_phisher/client/application.py", line
471, in server_connect
    server_version_info = rpc('version')
  File "/usr/local/lib/python2.7/dist-packages/AdvancedHTTPServer.py",
line 495, in __call__
    return self.call(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/AdvancedHTTPServer.py",
line 546, in call
    resp = self.client.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1073, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 379, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''

**Comment by seanjackson** [comment]
i am running 1.1.0 the image i sent you on the other issueCan you kindly look it up for me

**Comment by seanjackson** [comment]
updated my kali VM was surprised it wasnt updated to the lastest version

**Comment by zeroSteiner** [comment]
@seanjackson for the third and final time, please continue the conversation in the ticket you originally opened at #242. Do not open new tickets for this issue, do not comment on closed issues which you haven't opened for this issue.

Now v1.1.0 is quite old, we need you to upgrade to the latest version. We can't maintain support when you're about a year and a half out of date. Please upgrade both the client and server to version 1.8 and comment in #242 if you're still experiencing the same issue.
